name: moodink2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.3.0
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  path_provider: ^2.0.15
  path: ^1.8.3
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
  assets:
    - assets/fonts/


